```{r}
rm(list = ls())
# remotes::install_github("YuLab-SMU/createKEGGdb")
# library(createKEGGdb)
# species <-c("hsa")
# create_kegg_db(species)
library(clusterProfiler)
library(KEGG.db)
library(ggplot2)
library(pathview)
setwd("/Path/to/osteoporosis_sarcopenia_analysis/")
```

## KEGG analysis
```{r}
# Import gene list
# gene_list <- diffgene_selected[,"X"]
# This gene list was selected using Cytoscape and is used in the manuscript. You may replace it with any gene list you have obtained.
gene_list <- c("BCL6", "DDIT4", "FOXO3", "FLNA", "FOXO1", "IRS1", "NFKBIA", "PGK1", "STAT3") 

### ENSEMBL,SYMBOL,ENTREZID
gene = bitr(gene_list, 
            fromType="SYMBOL", 
            toType="ENTREZID", 
            OrgDb="org.Hs.eg.db")

EGG <- enrichKEGG(gene = gene$ENTREZID,
                  organism = 'hsa',
                  pvalueCutoff = 0.05,
                  use_internal_data =T)

projecr_path <- getwd()
output_dir   <- paste0(projecr_path, "/output_degs/Kegg_GO/")
output_file  <- paste0(output_dir, "os_sa_hub_genes_kegg.pdf")
pdf(output_file)  
barplot(EGG)
dotplot(EGG)
dev.off()
```

## [optional] you can check any specific KEGG pathwy
```{r}
KEGG_df    <- as.data.frame(EGG)
symboldata <- setReadable(EGG, OrgDb="org.Hs.eg.db", keyType = "ENTREZID")
symboldata <- as.data.frame(symboldata )
symboldata
browseKEGG(EGG, 'hsa04931')

output_dir   <- paste0(projecr_path, "/output_degs/Kegg_GO/")
output_file  <- paste0(output_dir, "kegg_hsa04931.pdf")
output_file
save(EGG,file = output_file)
```

### 示例：可视化一个具体的KEGG通路，例如 hsa04110 (细胞周期)
```{r}
# 安装和加载pathview
# BiocManager::install("pathview")
pathway.id <- "hsa04068"
pathview(gene.data = gene_entrez$ENTREZID,
         pathway.id = pathway.id,
         species = "hsa",
         gene.idtype = "ENTREZID")

output_dir <- paste0(work_dir, "/output_degs/Kegg_GO/")
setwd(output_dir)
for(pathway.id in kegg_enrich$ID){
  print(pathway.id)
  pathview(gene.data = gene_entrez$ENTREZID,
         pathway.id = pathway.id,
         species = "hsa"
         ) 
}
```

#############################################################################
## Gene Ontology analysis
Gene Ontology analysis includes Molecular Function (MF), Cellular Component (CC), and Biological Process (BP)
```{r}
ego_all <- enrichGO(gene          = gene$ENTREZID,
                    OrgDb         = "org.Hs.eg.db",
                    ont           = "all",
                    pAdjustMethod = "BH",
                    pvalueCutoff  = 0.01,
                    qvalueCutoff  = 0.05,
                    readable      = TRUE)

output_dir   <- paste0(projecr_path, "/output_degs/Kegg_GO/")
output_file  <- paste0(output_dir, "os_sa_hub_genes_go.pdf")
pdf(output_file)
barplot(ego_all, split="ONTOLOGY",label_format = 60) + facet_grid(ONTOLOGY~., scale="free")
dev.off() 
```

```{r}
### 1.CC
ego <- enrichGO(gene          = gene$ENTREZID,
                OrgDb         = "org.Hs.eg.db",
                ont           = "CC",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.05,
                readable      = TRUE)
#View(ego)
ego@result
dotplot(ego, showCategory=10)

barplot(ego)
dotplot(ego)
goplot(ego)
```

```{r}
#### 2.MF
ego_MF <- enrichGO(gene          = gene$ENTREZID,
                   OrgDb         = "org.Hs.eg.db",
                   ont           = "MF",
                   pAdjustMethod = "BH",
                   pvalueCutoff  = 0.01,
                   qvalueCutoff  = 0.05,
                   readable      = TRUE)
barplot(ego_MF,label_format = 60)

dotplot(ego_MF)
goplot(ego_MF)

test <- as.data.frame(ego_MF)
dput(test$Description[1:10])
```

```{r}
### 3.BP
ego_BP <- enrichGO(gene          = gene$ENTREZID,
                   OrgDb         = "org.Hs.eg.db",
                   ont           = "BP",
                   pAdjustMethod = "BH",
                   pvalueCutoff  = 0.01,
                   qvalueCutoff  = 0.05,
                   readable      = TRUE)

barplot(ego_BP,label_format = 60)
test <- as.data.frame(ego_BP)
dput(test$Description[1:10])
```